### ISSUE TITLE
Crash in spirou_ccf_pipeline.py

### ISSUE THREAD

**Issue by pfouque58** [edermartioli/spirou-ccf#3]
Checking once more this package on recent data of Gl 699 after computing a drift file from FP data, I got the following crash:

...
Spectrum (666/683): 2665534t.fits OBJ=Gl699 BJD=2459515.698457 SNR=208.2 BERV=-21.640 km/s  V exposure 1 DRS=0.6.132
Spectrum (667/683): 2665535t.fits OBJ=Gl699 BJD=2459515.699421 SNR=207.5 BERV=-21.641 km/s  V exposure 2 DRS=0.6.132
Spectrum (668/683): 2665536t.fits OBJ=Gl699 BJD=2459515.700388 SNR=205.5 BERV=-21.643 km/s  V exposure 3 DRS=0.6.132
Spectrum (669/683): 2665537t.fits OBJ=Gl699 BJD=2459515.701356 SNR=206.4 BERV=-21.644 km/s  V exposure 4 DRS=0.6.132
Traceback (most recent call last):
  File "/Users/pfouque/Software/SPIRou_SLS/Eder/spirou-ccf/data/Gl699/../../spirou_ccf_pipeline.py", line 400, in <module>
    run_spirou_ccf(inputdata, ccf_mask, drifts, telluric_rv=options.telluric_ccf, use_efits=options.use_efits, normalize_ccfs=True, save_output=True, source_rv=options.source_rv, ccf_width=options.ccf_width, vel_sampling=options.vel_sampling, run_analysis=True, output_template=options.output_template, interp_with_gp=options.interp_with_gp, verbose=options.verbose, plot=options.plot)
  File "/Users/pfouque/Software/SPIRou_SLS/Eder/spirou-ccf/data/Gl699/../../spirou_ccf_pipeline.py", line 66, in run_spirou_ccf
    reduced = reduc_lib.reduce_timeseries_of_spectra(inputdata, ccf_mask, rvfile="", use_efits=use_efits, fix_gaps=False, max_gap_size=5.0, nsig_clip=4.0, align_spectra=True, vel_sampling=vel_sampling, min_window_size=float(ccf_width), tel_mask=tel_mask, h2o_mask=h2o_mask, telluric_rv=telluric_rv, ccf_width=ccf_width, source_rv=source_rv, output_template=output_template, interp_with_gp=interp_with_gp, verbose=verbose)
  File "/Users/pfouque/Software/SPIRou_SLS/Eder/spirou-ccf/reduc_lib.py", line 1570, in reduce_timeseries_of_spectra
    array_of_spectra = load_array_of_spirou_spectra(inputdata, rvfile=rvfile, correct_blaze=True, apply_berv=True, verbose=verbose, plot=False, plot_diagnostics=False)
  File "/Users/pfouque/Software/SPIRou_SLS/Eder/spirou-ccf/reduc_lib.py", line 175, in load_array_of_spirou_spectra
    print("Spectrum ({0}/{1}): {2} OBJ={3} BJD={4:.6f} SNR={5:.1f} BERV={6:.3f} km/s  {7} DRS={8}".format(i,len(inputdata)-1,inputdata[i],hdr['OBJECT'],spectrum['BJD_mid'],maxsnr,spectrum['BERV'], hdr["CMMTSEQ"].replace(", sequence 1 of 1",""),hdr['VERSION']))
ValueError: Unknown format code 'f' for object of type 'str'

This is v0.6 of the DRS and I just added some recent observations 273* and it seems this is where it crashes. Does it mean that the format of recent e.fits or t.fits has been changed (in v0.6) ? Can you check on your side?

Thanks

**Comment by pfouque58** [comment]
It seems to be due to some keywords like BERV and BJD which have NaN values for recent data (March 2022) reduced with v0.6. So the code does not seem to be the culprit :)
